name: CI
on:
  push:

jobs:     
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repository Contents
      uses: actions/checkout@main
      with:
        repository: 'fastai/fastai2'
   
    - name: Copy This Repository Contents
      uses: actions/checkout@main
      with:
        path: 'docker/'
       
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
